# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
os:
  - linux
language: R
sudo: false
cache: packages

r_check_args: '--as-cran --use-valgrind'

env:
  - VALGRIND_OPTS='--tool=memcheck --leak-check=full --track-origins=yes'

addons:
  apt:
    packages:
      - valgrind
      
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'