// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// psrank
Rcpp::NumericVector psrank(Rcpp::NumericVector& data, Rcpp::NumericVector& group, Rcpp::NumericVector& n);
RcppExport SEXP _pseudorank_psrank(SEXP dataSEXP, SEXP groupSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(psrank(data, group, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pseudorank_psrank", (DL_FUNC) &_pseudorank_psrank, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_pseudorank(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
