# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

psrank <- function(data, group, n) {
    .Call(`_pseudorank_psrank`, data, group, n)
}

